#!/bin/sh
# Copied from https://github.com/dcreager/dotfiles/blob/main/install for importing these neovim configs
# (VERY IMPORTANT TODO!!: Fix this because it is relying on his config!! And.. Figure out how he structures his stuff because it's actually worth looking at(
if [ -z "$USER" ]; then
    USER=$(id -un)
fi

echo >&2 "====================================================================="
echo >&2 " Setting up codespaces environment"
echo >&2 ""
echo >&2 " USER        $USER"
echo >&2 " HOME        $HOME"
echo >&2 "====================================================================="

cd $HOME

# Make passwordless sudo work
export SUDO_ASKPASS=/bin/true

# A bit of a hack
mv .gitconfig .gitconfig.private

git clone https://github.com/dcreager/dotfiles-base .dotfiles.base
git clone https://github.com/dcreager/dotfiles-public -b codespaces --recurse-submodules .dotfiles.public
$HOME/.dotfiles.base/bin/dotfiles.symlink install

# Install fzf
FZF_VERSION=0.30.0
curl -L https://github.com/junegunn/fzf/releases/download/${FZF_VERSION}/fzf-${FZF_VERSION}-linux_amd64.tar.gz | tar xzC $HOME/bin

# Install neovim
NVIM_VERSION=0.7.0
sudo apt-get install -y libfuse2
curl -L -o $HOME/bin/nvim https://github.com/neovim/neovim/releases/download/v${NVIM_VERSION}/nvim.appimage
chmod a+x $HOME/bin/nvim
